name: build-and-publish
on: workflow_dispatch
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10.0.0
      - name: Install Node.js with pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --shamefully-hoist

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.74

      - run: pnpm build

#      - uses: JS-DevTools/npm-publish@v1
#        with:
#          token: ${{ secrets.NPM_TOKEN }}
