name: Deploy

on: workflow_dispatch

permissions:
  id-token: write
  contents: write

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup and build
        uses: ./.github/actions/setup-and-build

      - name: Read version from package.json
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Check whether this version is already published
        run: |
          if git ls-remote --exit-code --tags origin "refs/tags/${{ env.version }}" > /dev/null; then
            echo "Version ${{ env.version }} is already tagged."
            exit 1
          fi

      - name: Publish to NPM
        run: npm publish --access public

      - name: Create Git tag
        run: |
          git tag ${{ env.version }}
          git push origin ${{ env.version }}
