name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup and build
        uses: ./.github/actions/setup-and-build

      - name: Run lint
        run: pnpm --color run lint
